project_id = "kwlpufegfdipbhltluzr"

[functions.extract-pdf-data]
verify_jwt = false

[functions.doctor-auth]
verify_jwt = false

[functions.doctor-portal-data]
verify_jwt = false

[functions.validate-impersonation]
verify_jwt = false

[functions.impersonate-tenant]
verify_jwt = false

[functions.create-tenant-admin]
verify_jwt = false

[functions.sieg-sync]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
